{"uuid": "91118089-e961-4ba0-8db2-95c761216988", "children": ["9ae19544-87f0-48a5-aaf5-8ce585def128"], "befores": [{"name": "add_user_btn", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"d:\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"D:\\Test_APP\\scripts\\test_add_p001.py\", line 35, in add_user_btn\n    self.Add_obj.add_button()\n  File \".\\Page\\Page_Obj.py\", line 11, in add_button\n    self.click_element(Page.add_btn)\n  File \".\\Base\\Base.py\", line 21, in click_element\n    self.find_element(loc)\n  File \".\\Base\\Base.py\", line 9, in find_element\n    return WebDriverWait(self.driver,timeout,poll).until(lambda x: x.find_element(*loc))\n  File \"d:\\python\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1593864007572, "stop": 1593864017882}], "start": 1593864007572, "stop": 1593864017933}